name: model_factory
description: A code generator that creates .fake() methods for annotated data classes.
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: ^1.15.0

dev_dependencies:
  build_runner: ^2.4.0
  source_gen: ^1.5.0
  analyzer: ^6.0.0
  lints: ^5.0.0
  test: ^1.25.0
